version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

executors:
  openjdk-8:
    docker:
      - image: circleci/openjdk:8
  openjdk-11:
    docker:
      - image: circleci/openjdk:11

jobs:
  maven:
    parameters:
      executor:
        type: "string"
    executor:
      name: << parameters.executor >>
    steps:
      - checkout
      - run: ./mvnw clean package
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
      - codecov/upload:
          file: "coverage/target/site/jacoco-aggregate/jacoco.xml"

  integration-tests:
    parameters:
      executor:
        type: "string"
    executor:
      name: << parameters.executor >>
    steps:
      - checkout
      - run: ./mvnw clean package -Dmaven.test.skip=true
      - run: ./integration-test/<< parameters.executor >>/string-reverse/test.sh
      - run: ./integration-test/<< parameters.executor >>/pojo/test.sh
      - run: ./integration-test/<< parameters.executor >>/pojo-gson/test.sh
      - run: ./integration-test/<< parameters.executor >>/pojo-jackson/test.sh
      - run: ./integration-test/<< parameters.executor >>/exception/test.sh

workflows:
  ci:
    jobs:
      - maven:
          matrix:
            parameters:
              executor: ["openjdk-8", "openjdk-11"]
      - integration-tests:
          matrix:
            parameters:
              executor: [ "openjdk-8", "openjdk-11" ]
