version: 2.1

executors:
  openjdk-8:
    docker:
      - image: circleci/openjdk:8
  openjdk-11:
    docker:
      - image: circleci/openjdk:11

jobs:
  maven:
    parameters:
      executor:
        type: "string"
    executor:
      name: << parameters.executor >>
    steps:
      - checkout
      # Install dependencies that are not yet available at Maven central
      - run: git clone https://github.com/cloudevents/sdk-java.git
      - run: cd sdk-java && ./mvnw install
      - run: cd ..
      # Run the actual build...
      - run: ./mvnw package

workflows:
  ci:
    jobs:
      - maven:
          matrix:
            parameters:
              executor: ["openjdk-8", "openjdk-11"]
