name: Build
on:
  pull_request:
  push:
    branches: [main] # Avoid duplicate builds on PRs.
permissions:
  contents: read
  checks: write
  statuses: write
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version: [11, 8]
        os: [windows-latest, ubuntu-latest, macos-latest]
    name: Java ${{ matrix.version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.version }}
          distribution: zulu
          cache: maven
      - run: ./mvnw --no-transfer-progress clean package
      - run: ./integration-test/openjdk-${{ matrix.version }}/string-reverse/test.sh
        if: ${{ matrix.os != 'windows-latest' }}
      - run: ./integration-test/openjdk-${{ matrix.version }}/pojo/test.sh
      - uses: dorny/test-reporter@v1
        name: Test Report
        if: ${{ always() }}
        with:
          name: JUnit / ${{ matrix.version }} / ${{ matrix.os }}
          reporter: java-junit
          path: "**/target/surefire-reports/TEST-*.xml"

