name: Build
on:
  pull_request:
  push:
    branches: [main] # Avoid duplicate builds on PRs.
permissions:
  contents: read
  checks: write
  statuses: write
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version: [11, 8]
        os: [windows-latest, ubuntu-latest, macos-latest]
    name: Build / Java ${{ matrix.version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.version }}
          distribution: zulu
          cache: maven
      - run: ./mvnw --batch-mode clean package
      - uses: dorny/test-reporter@v1
        name: Test Report
        if: ${{ always() }}
        with:
          name: JUnit Report / Java ${{ matrix.version }} / ${{ matrix.os }}
          reporter: java-junit
          path: "**/target/surefire-reports/TEST-*.xml"

  integration:
    strategy:
      fail-fast: false
      matrix:
        version: [11, 8]
        os: [ubuntu-latest, macos-latest]
    name: Integration / ${{ matrix.version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.version }}
          distribution: zulu
          cache: maven
      - run: ./mvnw --batch-mode clean package -Dmaven.test.skip=true
      - run: ./integration-test/openjdk-${{ matrix.version }}/string-reverse/test.sh
      - run: ./integration-test/openjdk-${{ matrix.version }}/pojo/test.sh
      - run: ./integration-test/openjdk-${{ matrix.version }}/pojo-gson/test.sh
      - run: ./integration-test/openjdk-${{ matrix.version }}/pojo-jackson/test.sh
      - run: ./integration-test/openjdk-${{ matrix.version }}/list-pojo/test.sh
      - run: ./integration-test/openjdk-${{ matrix.version }}/exception/test.sh
      - run: ./integration-test/openjdk-${{ matrix.version }}/sdk-1.1.0/test.sh
      - run: ./integration-test/openjdk-${{ matrix.version }}/sdk-1.1.1/test.sh

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu
          cache: maven
      - run: ./mvnw clean package -Paggregate-coverage
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/target/site/jacoco-aggregate/jacoco.xml
