name: forcedotcom/sf-fx-runtime-java/ci
on:
  push:
env:
  CODECOV_TOKEN: xxxxxxx
jobs:
  coverage-report:
    runs-on: sfdc-hk-ubuntu-latest
    container:
      image: openjdk:11
    steps:
    - uses: actions/checkout@v2
    - run: "./mvnw clean package -Paggregate-coverage"
#     # This item has no matching transformer
#     - codecov_codecov_upload:
  maven-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: mvnw.cmd clean package -Dmaven.javadoc.skip=true
  maven:
    runs-on: sfdc-hk-ubuntu-latest
    strategy:
      matrix:
        executor:
        - openjdk-8
        - openjdk-11
    steps:
    - uses: actions/checkout@v2
    - run: "./mvnw clean package"
    - name: Save test results
      run: |-
        mkdir -p ~/test-results/junit/
        find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
      if: always()
    - uses: actions/upload-artifact@v2
      with:
        path: "~/test-results"
    - uses: actions/upload-artifact@v2
      with:
        path: "~/test-results/junit"
  integration-tests:
    runs-on: sfdc-hk-ubuntu-latest
    strategy:
      matrix:
        executor:
        - openjdk-8
        - openjdk-11
    steps:
    - uses: actions/checkout@v2
    - run: "./mvnw clean package -Dmaven.test.skip=true"
    - run: "./integration-test/${{ matrix.executor }}/string-reverse/test.sh"
    - run: "./integration-test/${{ matrix.executor }}/pojo/test.sh"
    - run: "./integration-test/${{ matrix.executor }}/pojo-gson/test.sh"
    - run: "./integration-test/${{ matrix.executor }}/pojo-jackson/test.sh"
    - run: "./integration-test/${{ matrix.executor }}/list-pojo/test.sh"
    - run: "./integration-test/${{ matrix.executor }}/exception/test.sh"
    - run: "./integration-test/${{ matrix.executor }}/sdk-1.1.0/test.sh"
